### PR TITLE
Changed MainActivity to BottomNavActivity

### PR DESCRIPTION
**Pull request by tchell**
- Changed the MainActivity to the default BottomNavActivity.
- Added a top toolbar so that its easier to implement things like
settings, logging in, logging out, etc.
- Added dependencies for Espresso, Firebase
- Fixed a couple things messed up with the Tests, and Model classes
#34

### CODE REVIEW

**Review by NErgezinger — COMMENTED** [review]
If we're going to have a link to download google-services.json, we may as well just have it in the repo

**Comment by tchell** [comment]
> If we're going to have a link to download google-services.json, we may as well just have it in the repo

It requires permission to download though so only we can download it.

**Comment by NErgezinger** [comment]
> > If we're going to have a link to download google-services.json, we may as well just have it in the repo
> 
> It requires permission to download though so only we can download it.

Oh ok that's fine then

**Review by NErgezinger — APPROVED** [review]

**Review by bclue — APPROVED** [review]
Seems good to me.

**Pull request merged**
